name: Build Lambda Layer

on:
  pull_request:
    branches: [ master ]

jobs:
  
  deploy:
    name: Upload Layer to AWS Lambda
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-3

      - name: Zip it all up and upload to S3
        env:
          release_bucket: deploy-layer
          release_bucket_uri: s3://deploy-layer
          release_id: ${{ format('<REPO NAME>-{0}-dev.zip', github.head_ref )}}
          release_layer: ${{ format('<REPO NAME>-{0}-dev', github.head_ref )}}
        run: |
          echo building release $release_id

